# Generated by Django 5.0.5 on 2024-05-07 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_as_category', to='category.category')),
                ('type_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='category.category')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
